# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYzpq9QmN8ZPqnbUGfgjBRWyEvcTgHJ3
"""

import pandas as pd
data=pd.read_csv("/content/titanic (1).csv")
data

data.isnull()

data.head(5)

data.info()

data.isnull().sum()

import numpy as np
from scipy import stats
mean1 = np.mean(data['Age'])
median1 = np.median(data['Age'])
mode1=stats.mode(data['Age'],keepdims = True).mode[0]
mean2 = np.mean(data['Fare'])
median2 = np.median(data['Fare'])
mode2=stats.mode(data['Fare'],keepdims = True).mode[0]
print("Central Trndency:")
print("mean Age:",mean1)
print("median Age:",median1)
print("mode Age:",mode1)
print("mean Fare:",mean2)
print("median Fare:",median2)
print("mode Fare:",mode2)

import pandas as pd
data['Survived'] = data['Survived'].replace({1: 'survived', 0: 'not survived'})
print(data['Survived'])

import pandas as pd
import matplotlib.pyplot as plt
grouped_data = data.groupby(['Survived', 'Pclass']) ['PassengerId']. count().unstack()
grouped_data.plot(kind='bar', figsize=(10, 6))
plt.title('Survival Counts by Pclass')
plt.xlabel('Survival')
plt.ylabel('Count')
plt.xticks ( ticks=[0, 1], labels=['0', '1'],rotation=0)
plt.legend(title='Pclass')
plt.show()

import pandas as pd
url = "/content/titanic (1).csv"
titanic_df = pd.read_csv(url)
titanic_df
null_values = titanic_df.isnull().sum()
titanic_filled_df = titanic_df.fillna(titanic_df.mean(numeric_only=True))
null_values, titanic_filled_df.head()

import numpy as np
mean = np.mean(data['Age'])
std=np.std(data['Age'])
print('mean of the dataset is',mean)
print('std. deviation is',std)

threshold = 3
outlier = []
for i in data['Age']:
  z=(i-mean)/std
  if z> threshold:
    outlier.append(i)
print('outlier in dataset is', outlier)

import seaborn as sns
sns.boxplot(data['Age'])